# Part 1

**You are given the following dataset representing students’ grades in 4 subjects:**

In [94]:
import numpy as np


In [52]:
grades =[[85, 78, 92, 88],
[70, 76, 80, 65],
[90, 88, 94, 91],
[60, 65, 58, 62],
[100, 95, 98, 97]] 

**Convert the data into a NumPy array.**


In [53]:
grades_array = np.array(grades)

**shape of array**

In [54]:
print(f"the shape of the array is: {grades_array.shape}")

the shape of the array is: (5, 4)


**The mean grade of each student**
**The mean grade of each subject.**

In [55]:
# *The mean grade of each student*
the_mean = np.mean(grades_array)
print(f"the mean of the grades is: {the_mean}")
# **The mean grade of each subject.**
the_mean_subject = np.mean(grades_array, axis=0)
print(f"the mean of the grades for each subject is: {the_mean_subject}")

the mean of the grades is: 81.6
the mean of the grades for each subject is: [81.  80.4 84.4 80.6]


**• Extract the students whose average grade is greater than 85.**

In [56]:
the_avr_subject = np.average(grades_array, axis=1)
for i in range(len(the_avr_subject)):
    if the_avr_subject[i] >85:
        print(f"the average grade of student {i+1} is: {the_avr_subject[i]} and it is above 85")
    

the average grade of student 1 is: 85.75 and it is above 85
the average grade of student 3 is: 90.75 and it is above 85
the average grade of student 5 is: 97.5 and it is above 85


**Add a bonus of 5 marks to all grades using broadcasting.**

In [57]:
# Add a bonus of 5 marks to all grades using broadcasting. 
grades_array += 5
print(f"the grades after adding the bonus are: \n{grades_array}")

the grades after adding the bonus are: 
[[ 90  83  97  93]
 [ 75  81  85  70]
 [ 95  93  99  96]
 [ 65  70  63  67]
 [105 100 103 102]]


**• Normalize the grades using Min-Max normalization.**

In [58]:
 
min_grades = np.min(grades_array)
max_grades = np.max(grades_array)
normalized_grades = (grades_array - min_grades) / (max_grades - min_grades)
print(f"the normalized grades are: \n{normalized_grades}")

the normalized grades are: 
[[0.64285714 0.47619048 0.80952381 0.71428571]
 [0.28571429 0.42857143 0.52380952 0.16666667]
 [0.76190476 0.71428571 0.85714286 0.78571429]
 [0.04761905 0.16666667 0.         0.0952381 ]
 [1.         0.88095238 0.95238095 0.92857143]]


**Flatten the array into a single vector.**

In [59]:
 
flattened_grades = grades_array.flatten()
print(f"the flattened grades are: \n{flattened_grades}")

the flattened grades are: 
[ 90  83  97  93  75  81  85  70  95  93  99  96  65  70  63  67 105 100
 103 102]


# Part 2

**Linear Regression from Scratch (Normal Equation)**

In [61]:
house_size=[50, 60, 80, 100, 120]  
price_in_thousands=[150, 180, 240, 300, 330]  

In [62]:
# convert the lists to numpy arrays
x=np.array(house_size)
y=np.array(price_in_thousands)

In [71]:
# reshape the arrays to be 2D
x=x.reshape(-1, 1)
y=y.reshape(-1, 1)


In [101]:
# • Add a bias column of ones to X.
X = np.hstack((x, np.ones((x.shape[0], 1))))
X

array([[ 50.,   1.],
       [ 60.,   1.],
       [ 80.,   1.],
       [100.,   1.],
       [120.,   1.]])

In [102]:
print(f"the shape of X is: {X.shape} \n the shape of y is: {y.shape}")

the shape of X is: (5, 2) 
 the shape of y is: (5, 1)


In [103]:
# Compute the parameter vector θ using the Normal Equation: θ = (X^T X)^(-1) X^T y.
theta = np.linalg.inv(X.T @ X) @ X.T @ y

In [105]:
# • Use the computed θ to predict the price of a 90 m² house. 
new_house = np.array([[90, 1]])  # 90 m² with bias term
predicted_price = new_house @ theta
print(f"the predicted price of a 90 m² house is: {predicted_price[0][0]} thousand dollars")

the predicted price of a 90 m² house is: 261.2195121951215 thousand dollars
